#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 21 11:35:22 2021

@author: johnm

Affix and search result validation.
"""

from syllysql import sql
import pandas as pd

print(sql.get_table('affix_table'))
affix_dataframe = pd.DataFrame(columns = ['affix', 'category', 'type', 'position', 'derivative'])
basic_dictionary = {'affix': '', 'category': '', 'type': '', 'position': '', 'part of speech' : '', 'derivative' : 'no'}

inflection_list = [
                  {'affix': 's', 'category': 'number', 'type': 'plural', 'position': 'suffix', 'part of speech' : 'noun', 'derivative' : 'no'},
                  {'affix': 'self', 'category': 'case', 'type': 'reflexive', 'position': 'suffix', 'part of speech' : 'pronoun', 'derivative' : 'no'},
                  {'affix': 'ing', 'category': 'aspect', 'type': 'progressive', 'position': 'suffix', 'part of speech' : 'verb', 'derivative' : 'no'},
                  {'affix': 'en', 'category': 'aspect', 'type': 'perfect non-progressive', 'position': 'suffix', 'part of speech' : 'verb', 'derivative' : 'no'},
                  {'affix': 'ed', 'category': 'aspect', 'type': 'perfect non-progressive', 'position': 'suffix', 'part of speech' : 'verb', 'derivative' : 'no'},
                  {'affix': 'ed', 'category': 'tense', 'type': 'past', 'position': 'suffix', 'part of speech' : 'verb', 'derivative' : 'no'},
                  {'affix': 's', 'category': 'person', 'type': '3rd person singular present', 'position': '', 'part of speech' : 'verb', 'derivative' : 'no'},
                  {'affix': 'er', 'category': 'degree of comparison', 'type': 'comparative', 'position': '', 'part of speech' : 'adjective', 'derivative' : 'no'},
                  {'affix': 'est', 'category': 'degree of comparison', 'type': 'superlative', 'position': '', 'part of speech' : 'adjective', 'derivative' : 'no'}
                  ]
inflection_df = pd.DataFrame(inflection_list)


print(sql.get_table('affix_table'))
print(sql.get_table(''))